[package]
name = "fist_macro"
version = "0.1.0"
authors = ["huangyinglun <503375725@qq.com>"]
description = "fist macro_proc"
keywords = ["template", "proc_macro", "procmacro"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = "1.0"

